# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swiftly
subtitle: Swift 5.1 references for busy coders
description: Swiftly is a one-stop quick reference spot for Swift developers, covering Swift basics, control flow, types, structs/classes, operators, functional methods, and more.
author: Eugene Belinski
keywords: 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap